apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yolo-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/ahmadry98/PolyAIFursa.git
    targetRevision: dev
    path: infra/k8s/dev/yolo

  destination:
    server: https://kubernetes.default.svc
    namespace: dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true