services:
  frontend:
    image: "${FRONTEND_IMAGE}:${FRONTEND_IMAGE_TAG}"
    ports:
      - "3000:3000"
    networks:
      - polyai-net

  agent:
    image: "${AGENT_IMAGE}:${AGENT_IMAGE_TAG}"
    env_file:
      - ./services/agent/.env
    environment:
      YOLO_SERVICE_URL: http://yolo:8080
      IMG_PROC_MCP_URL: http://img-proc-mcp:9000
      AWS_REGION: "${AWS_REGION:-us-east-1}"
    ports:
      - "8000:8000"
    depends_on:
      - yolo
      - img-proc-mcp
    networks:
      - polyai-net

  yolo:
    image: "${YOLO_IMAGE}:${YOLO_IMAGE_TAG}"
    env_file:
      - ./services/agent/.env
    environment:
      AWS_REGION: "${AWS_REGION:-us-east-1}"
    networks:
      - polyai-net
  img-proc-mcp:
    image: "${IMG_PROC_MCP_IMAGE}:${IMG_PROC_MCP_IMAGE_TAG}"
    ports:
      - "9000:9000"
    networks:
      - polyai-net 
  node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node-exporter
    command:
      - '--path.rootfs=/host'
      - '--collector.processes'
    network_mode: host
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    depends_on:
      - yolo
      - node-exporter
    networks:
      - polyai-net
      - monitoring-net
    extra_hosts:
      - "host.docker.internal:host-gateway"

  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards:ro
    depends_on:
      - prometheus
    networks:
      - monitoring-net

  fluent-bit:
    image: fluent/fluent-bit:4.2.7
    environment:
      AWS_REGION: "${AWS_REGION:-us-east-1}"
      FLUENT_BIT_S3_BUCKET: "${FLUENT_BIT_S3_BUCKET:-ahmad-polyai-logs}"
    volumes:
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/log:/var/log
    depends_on:
      - frontend
      - agent
      - yolo
      - img-proc-mcp
    networks:
      - monitoring-net


volumes:
  prometheus-data:
  grafana-data:

networks:
  polyai-net:
  monitoring-net:
