apiVersion: v1
kind: Service
metadata:
  name: yolo-svc
  labels:
    app.kubernetes.io/name: yolo
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: yolo
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
