apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: yolo-rs
  namespace: workloads-lab
  labels:
    app: yolo-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: yolo-service
  template:
    metadata:
      labels:
        app: yolo-service
    spec:
      containers:
      - name: server
        image: docker.io/ahmadray98/polyai-fursa-yolo:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
