apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yolo
  template:
    metadata:
      labels:
        app: yolo
    spec:
      containers:
        - name: yolo
          image: docker.io/ahmadray98/polyai-fursa-yolo:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: AWS_S3_BUCKET
              value: ahmad-polyai-images
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 20
          resources:
            requests:
              cpu: "100m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "2Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: yolo-svc
spec:
  type: ClusterIP
  selector:
    app: yolo
  ports:
    - port: 8080
      targetPort: 8080
