node:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: DoesNotExist
              - key: eks.amazonaws.com/compute-type
                operator: NotIn
                values:
                  - fargate
                  - auto
                  - hybrid
