name: Docker Scout

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - main

jobs:
  scout-yolo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build YOLO image
        uses: docker/build-push-action@v6
        with:
          context: ./services/yolo
          push: false
          tags: yolo-service:scout

      - name: Docker Scout scan
        uses: docker/scout-action@v1
        with:
          command: cves
          image: yolo-service:scout
          only-severities: critical,high
          exit-code: false
